name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - name: Build Hugo website
      run: hugo --minify

    - name: Authenticate Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
      run: gcloud auth login

    - name: Deploy to Google Cloud Storage
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
      run: gcloud storage cp --recursive public/* gs://$BUCKET_NAME
