name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_KEY }}

    - name: Build Hugo website
      run: hugo --minify

    - name: Deploy to Google Cloud Storage
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      run: gcloud storage cp --recursive public/* gs://$BUCKET_NAME
      